#!/usr/bin/env bash

while [[ $# -gt 0 ]] 
do
  case $1 in
    e|edit )
      EDIT="true"
      shift
      ;;

    g|git )
      GIT="true"
      shift
      ;;

    x|terminal )
      TERMINAL="true"
      shift
      ;;

    *)
      echo "Option ${1} is not supported by this command"
      shift
      ;;
  esac
done

if [ $EDIT ] 
then
  $APPLICATION_LIB_DIR/windows/editor-window d
fi

if [ $GIT ] 
then
  $APPLICATION_LIB_DIR/windows/git-window d
fi

if [ $TERMINAL ] 
then
  $APPLICATION_LIB_DIR/windows/terminal-window d
fi
